### PR TITLE
Fix 12.34f syntax

### LINKED ISSUE #193: implicit conversion from int to float doesn't work
```jou
from "stdlib/io.jou" import printf

def show_float(x: float) -> void:
    printf("%.2f\n", x)

def main() -> int:
    show_float(5)
    return 0
```

Expected output: `5.00`
Actual output: `0.00`

### LINKED ISSUE #194: 12.34F syntax doesn't work
```
from "stdlib/io.jou" import printf

def main() -> int:
    x = 12.34F
    y = 56.78f
    printf("%.2f %.2f\n", x, y)
    return 0
```

Expected output: `12.34 56.78`
Actual output: `compiler error in file "asd.jou", line 4: invalid number or variable name "12.34F"`

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #194 
Fixes #193

### CODE REVIEW

File: src/codegen.c [hunk 1]
```diff
@@ -284,8 +284,9 @@ static void codegen_instruction(const struct State *st, const CfInstruction *ins
                         setdest(LLVMBuildSIToFP(st->builder, getop(0), codegen_type(to), "cast"));
                     else
                         setdest(LLVMBuildUIToFP(st->builder, getop(0), codegen_type(to), "cast"));
+                } else if ((from == floatType || from == doubleType) && (to == floatType || to == doubleType)) {
+                    setdest(LLVMBuildFPCast(st->builder, getop(0), codegen_type(to), "cast"));
                 } else {
-                    // TODO: integer --> double / float
                     assert(0);
```
Comment (Akuli) [inline src/codegen.c:290]:
```suggestion
                    // TODO: double/float --> integer
                    assert(0);
```

File: src/tokenize.c [hunk 2]
```diff
@@ -396,10 +396,16 @@ static Token read_token(struct State *st)
                 if (is_keyword(t.data.name))
                     t.type = TOKEN_KEYWORD;
                 else if ('0'<=t.data.name[0] && t.data.name[0]<='9') {
-                    if (is_valid_double(t.data.name))
-                        t.type = TOKEN_DOUBLE;
-                    else if (t.data.name[strlen(t.data.name)-1] == 'F' && is_valid_double(t.data.name))
+                    if ((t.data.name[strlen(t.data.name)-1] == 'F' || t.data.name[strlen(t.data.name)-1] == 'f')
+                        && strncmp(t.data.name, "0x", 2)) // no error for 0xff
```
Comment (Akuli) [inline src/tokenize.c:400]:
```suggestion
                        && strncmp(t.data.name, "0x", 2)) // 0xff is not a float
```
