### PR TITLE
Pointer comparisons

### LINKED ISSUE #279: cannot >= compare pointers
this doesn't work

```
    for p = &digits[strlen(digits) - 1]; p >= digits; p--:
```

this works

```
    for i = strlen(digits) - 1; i >= 0; i--:
```

I think both should work.

### PR DESCRIPTION
**Pull request by Akuli**
E.g. `&foo[0] < &foo[1]`. Fixes #279

### CODE REVIEW

File: src/typecheck.c [hunk 1]
```diff
@@ -641,7 +642,7 @@ static const Type *check_binop(
     if (got_numbers && !got_integers)
         cast_type = (lhstypes->type == doubleType || rhstypes->type == doubleType) ? doubleType : floatType;
     if (got_pointers)
-        cast_type = voidPtrType;
+        cast_type = longType;
```
Comment (Akuli) [inline src/typecheck.c:645]: Could be slightly safer to use unsigned long

```suggestion
        cast_type = get_integer_type(64, false);  // unsigned long
```

File: src/tokenize.c [hunk 2]
```diff
@@ -80,15 +80,15 @@ static void read_identifier_or_number(struct State *st, char firstbyte, char (*d
 
     assert(is_identifier_or_number_byte(firstbyte));
     (*dest)[destlen++] = firstbyte;
+    bool is_number = '0'<=firstbyte && firstbyte<='9';
```
Comment (Akuli) [inline src/tokenize.c:83]: Nice, but doesn't belong to this PR.
