### PR TITLE
Fix the weird sizeof bug

### LINKED ISSUE #224: Valgrind error on a compiled executable when optimizations are enabled
content of `bug.jou`:

```
from "stdlib/mem.jou" import malloc

struct Token:
    kind: int
    path: byte*
    lineno: int
    lineno2: int
    int_value: int
    long_value: long
    byte_value: byte
    indentation_level: int
    short_string: byte[100]

def foo() -> Token*:
    tokens: Token* = NULL
    tokens = malloc(sizeof(tokens[0]))
    tokens[0] = Token{kind = 1}
    return tokens

def main() -> int:
    foo()
    return 0
```

Running it under valgrind on Linux:

```
$ ./jou -o asd -O1 bug.jou
$ valgrind ./asd
```

Expected result: no valgrind errors except the leak.
Actual result: `Invalid write` error
```
==20167== Memcheck, a memory error detector
==20167== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20167== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==20167== Command: ./asd
==20167== 
==20167== Invalid write of size 8
==20167==    at 0x401152: foo (in /home/akuli/jou/asd)
==20167==    by 0x40119F: ??? (in /home/akuli/jou/asd)
==20167==    by 0x4011A5: main (in /home/akuli/jou/asd)
==20167==  Address 0x4b810cc is 140 bytes inside a block of size 144 alloc'd
==20167==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==20167==    by 0x40113A: foo (in /home/akuli/jou/asd)
==20167==    by 0x40119F: ??? (in /home/akuli/jou/asd)
==20167==    by 0x4011A5: main (in /home/akuli/jou/asd)
==20167== 
==20167== 
==20167== HEAP SUMMARY:
==20167==     in use at exit: 144 bytes in 1 blocks
==20167==   total heap usage: 1 allocs, 0 frees, 144 bytes allocated
==20167== 
==20167== LEAK SUMMARY:
==20167==    definitely lost: 144 bytes in 1 blocks
==20167==    indirectly lost: 0 bytes in 0 blocks
==20167==      possibly lost: 0 bytes in 0 blocks
==20167==    still reachable: 0 bytes in 0 blocks
==20167==         suppressed: 0 bytes in 0 blocks
==20167== Rerun with --leak-check=full to see details of leaked memory
==20167== 
==20167== For lists of detected and suppressed errors, rerun with: -s
==20167== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #224 

Marking as a draft for now, because I haven't found a fix yet, although I added a test case.

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -11,6 +11,7 @@
 #include <llvm-c/Core.h>
 #include <llvm-c/Linker.h>
 #include <llvm-c/Transforms/PassManagerBuilder.h>
+#include <llvm-c/TargetMachine.h>
```
Comment (Akuli) [inline src/main.c:14]:
```suggestion
```

File: src/codegen.c [hunk 2]
```diff
@@ -5,6 +5,8 @@
 #include <string.h>
 #include <llvm-c/Core.h>
 #include <llvm-c/Types.h>
+#include <llvm-c/Target.h>
```
Comment (Akuli) [inline src/codegen.c:8]:
```suggestion
```

File: src/codegen.c [hunk 3]
```diff
@@ -5,6 +5,7 @@
 #include <string.h>
 #include <llvm-c/Core.h>
 #include <llvm-c/Types.h>
+#include <llvm-c/TargetMachine.h>
```
Comment (Akuli) [inline src/codegen.c:8]:
```suggestion
```
