### PR TITLE
O1 is the default in the help message

### LINKED ISSUE #463: help message optimization default wrong
https://github.com/Akuli/jou/blob/06c74f5b1e022f5283aa0c11a879893423423e4b/src/main.c#L43

Default was changed to 1 after this was written

### PR DESCRIPTION
**Pull request by littlewhitecloud**
fix #463
I am sorry I forgot to change that

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -32,6 +32,7 @@ static void optimize(LLVMModuleRef module, int level)
     LLVMDisposePassManager(pm);
 }
 
+/* Sync with tests/should_succeed/compiler_cli.jou */
```
Comment (Akuli) [inline src/main.c:35]: IMO we don't need this comment. You will notice if tests fail.

File: src/main.c [hunk 2]
```diff
@@ -40,7 +41,7 @@ static const char help_fmt[] =
     "\n"
     "Options:\n"
     "  -o OUTFILE       output an executable file, don't run the code\n"
-    "  -O0/-O1/-O2/-O3  set optimization level (0 = default, 3 = runs fastest)\n"
+    "  -O0/-O1/-O2/-O3  set optimization level (1 = default, 3 = runs fastest)\n"
```
Comment (Akuli) [inline src/main.c:44]: We could explain what 0 does:

```suggestion
    "  -O0/-O1/-O2/-O3  set optimization level (0 = no optimization, 1 = default, 3 = runs fastest)\n"
```

**Review by Akuli — APPROVED** [review]
Thanks!

**Comment by Akuli** [comment]
> I am sorry I forgot to change that

It's ok, things like this happen to everyone all the time :)
