### PR TITLE
Get rid of analyzable boolean

### LINKED ISSUE #15: No unreachable warning for some infinite loops
I'm preparing a pull request to show warnings for unreachable code, but it doesn't work in at least these two cases I tried:

```python
def after_infinite_loop_with_variable() -> void:
    flag = True
    while flag:
        puts("hi")
    puts("yooooo wat")  # Warning: this code will never run

def after_infinite_loop_with_variable_set_after_loop() -> void:
    flag = True
    while flag:
        puts("hi")
    flag = False  # Warning: this code will never run
```

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #15

### CODE REVIEW

File: src/simplify_cfg.c [hunk 1]
```diff
@@ -17,24 +17,49 @@ static int find_var_index(const struct CfGraph *cfg, const struct CfVariable *v)
...
-            did_something = true;
-        }
-        if (src[i].can_be_false && !dest[i].can_be_false) {
-            dest[i].can_be_false = 1;
+        enum BoolStatus newdest;
+
+        assert(src[i] != UNSET);
+        if (dest[i] == UNSET)
+            newdest = src[i];
+        if (src[i] == CAN_CHANGE_UNPREDICTABLY || dest[i] == CAN_CHANGE_UNPREDICTABLY)
```
Comment (Akuli) [inline src/simplify_cfg.c:48]:
```suggestion
        else if (src[i] == CAN_CHANGE_UNPREDICTABLY || dest[i] == CAN_CHANGE_UNPREDICTABLY)
```

File: src/simplify_cfg.c [hunk 2]
```diff
@@ -105,25 +128,35 @@ static struct BoolStatus **determine_known_bool_values(const struct CfGraph *cfg
...
-                else
-                    tempstatus[destidx] = (struct BoolStatus){ .can_be_true=1, .can_be_false=1 };
+                switch(tempstatus[find_var_index(cfg, ins->operands[0])]) {
+                case KNOWN_TO_BE_TRUE:
+                    tempstatus[destidx] = KNOWN_TO_BE_TRUE;
+                    break;
+                case KNOWN_TO_BE_FALSE:
+                    tempstatus[destidx] = KNOWN_TO_BE_FALSE;
+                    break;
+                case CAN_CHANGE_UNPREDICTABLY:  // Even a non-analyzable variable yields true or false value.
```
Comment (Akuli) [inline src/simplify_cfg.c:144]:
```suggestion
                case CAN_CHANGE_UNPREDICTABLY:  // Even an unpredictable variable yields true or false value.
```

File: src/simplify_cfg.c [hunk 3]
```diff
@@ -145,7 +178,7 @@ static struct BoolStatus **determine_known_bool_values(const struct CfGraph *cfg
 }
 
 #if 0
-static void dump_known_bool_values(const struct CfGraph *cfg, struct BoolStatus **statuses)
+static void dump_known_bool_values(const struct CfGraph *cfg, enum BoolStatus **statuses)
```
Comment (Akuli) [inline src/simplify_cfg.c:181]: This won't work anymore. Should delete.

File: src/simplify_cfg.c [hunk 4]
```diff
@@ -144,41 +221,28 @@ static struct BoolStatus **determine_known_bool_values(const struct CfGraph *cfg
...
-        }
-        if (!s.can_be_true && s.can_be_false) {
+            break;
+        case KNOWN_TO_BE_FALSE:
             // Always jump to false case.
             block->iftrue = block->iffalse;
+            break;
+        case UNSET:
+        case CAN_CHANGE_UNPREDICTABLY:
+        case COULD_BE_TRUE_OR_FALSE:
```
Comment (Akuli) [inline src/simplify_cfg.c:244]:
```suggestion
        default:
```
