### PR TITLE
doctest: Do not pass newline to "base64 -d"

### LINKED ISSUE #500: doctest netbsd base64 error
NetBSD test output contains:

```
Extracting doctests from doc/perf.md...
Extracting doctests from doc/syntax-spec.md...
Extracting doctests from doc/tutorial.md...
Extracting doctests from doc/ub.md...
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:147: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:171: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:193: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:279: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:304: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:323: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:340: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:407: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:423: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:438: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:466: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:506: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:518: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:538: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:56: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:622: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:68: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:96: ok
base64: Decoding failed: Inappropriate file type or format
doc/ub.md:131: ok
19 succeeded, 0 failed
```

Even though the test "succeeds", it would be nice to know what the errors are about and whether they are a bad thing.

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #500

### CODE REVIEW

File: doctest.sh [hunk 1]
```diff
@@ -77,7 +77,7 @@ nfail=0
 cd tmp/doctest
 for file in */*.jou; do
     # print file and line number, as in "doc/foo.md:123: "
```
Comment (Akuli) [inline doctest.sh:79]:
```suggestion
    # Print file and line number, as in "doc/foo.md:123: "
    # Newline is deleted to avoid warning on NetBSD 9.3, see issue #500
```
