### PR TITLE
Control flow graph

### LINKED ISSUE #3: No compile error, if you forget return
```python
cdecl puts(string: byte*) -> int

def main() -> int:
    puts("Hello World")
    # No return statement. Should not compile, but currently segfaults at runtime.
```

I wonder if I should ask LLVM whether the end of the function can be reached without a `return` statement, or should I check for that myself.

### PR DESCRIPTION
**Pull request by Akuli**
A new compile step / intermediate representation. Can be used to fix #3 and #5

### CODE REVIEW

File: src/build_cfg.c [hunk 1]
```diff
@@ -0,0 +1,357 @@
...
+    return build_cfg_for_implicit_cast(st, result, &expr->type_after_implicit_cast);
+}
+
+static struct CfVariable *build_cfg_for_address_of_expression(const struct State *st, const struct AstExpression *address_of_what)
+{
+    switch(address_of_what->kind) {
+    case AST_EXPR_GET_VARIABLE:
+        {
+            struct CfVariable *var = find_variable(st, address_of_what->data.varname);
+            // TODO: shouldn't need to create a new type here
```
Comment (Akuli) [inline src/build_cfg.c:223]: Or maybe it would be better to clone all types instead of referencing to them in AST?

File: src/build_cfg.c [hunk 2]
```diff
@@ -0,0 +1,357 @@
...
+    return return_value;
+}
+
+static void build_cfg_for_body(struct State *st, const struct AstBody *body);
+
+static void build_cfg_for_statement(struct State *st, const struct AstStatement *stmt)
+{
+    if (!st->current_block)
+        fail_with_error(stmt->location, "statement is unreachable, it can never run");
+
```
Comment (Akuli) [inline src/build_cfg.c:274]: This is not detected yet, I changed my mind about how to do this.

```suggestion
```

File: README.md [hunk 3]
```diff
@@ -103,13 +103,9 @@ The two types are the same when no casting needs to be done.
 For example, if you call `putchar(int)` with an argument of type `byte`,
```
Comment (Akuli) [inline README.md:103]: It says above AST is printed twice. Now 3 times.

File: src/codegen.c [hunk 4]
```diff
@@ -8,73 +8,79 @@
...
+        assert(0);
+    }
+    assert(0);
+}
 
 struct State {
     LLVMModuleRef module;
     LLVMBuilderRef builder;
     const struct AstFunctionDef *ast_func;
     LLVMValueRef llvm_func;
```
Comment (Akuli) [inline src/codegen.c:31]: do we still need ast_func? How about llvm_func?

File: src/codegen.c [hunk 5]
```diff
@@ -8,73 +8,79 @@
...
 
-static LLVMValueRef get_pointer_to_local_var(const struct State *st, const char *name)
+static LLVMValueRef get_pointer_to_local_var(const struct State *st, const struct CfVariable *cfvar)
 {
-    for (int i = 0; st->ast_func->locals[i].name[0]; i++)
-        if (!strcmp(st->ast_func->locals[i].name, name))
+    assert(cfvar);
+    for (int i = 0; i < st->ast_func->cfg->variables.len; i++) {
+        if (st->ast_func->cfg->variables.ptr[i] == cfvar) {
             return st->llvm_locals[i];
```
Comment (Akuli) [inline src/codegen.c:42]: This function is stupid. Maybe should calculate number of variables needed beforehand, so that I don't need to worry about growing the list and messing up old pointers? (That's why its a list of individually alloced pointers now)

File: src/codegen.c [hunk 6]
```diff
@@ -93,212 +99,142 @@ static LLVMValueRef make_a_string_constant(const struct State *st, const char *s
...
     char debug_name[100] = {0};
     if (LLVMGetTypeKind(LLVMGetReturnType(function_type)) != LLVMVoidTypeKind)
-        snprintf(debug_name, sizeof debug_name, "%s_return_value", call->funcname);
-
-    LLVMValueRef return_value = LLVMBuildCall2(st->builder, function_type, function, args, call->nargs, debug_name);
+        snprintf(debug_name, sizeof debug_name, "%s_return_value", funcname);
 
-    free(args);
+    LLVMValueRef return_value = LLVMBuildCall2(st->builder, function_type, function, args, nargs, debug_name);
     return return_value;
```
Comment (Akuli) [inline src/codegen.c:115]:
```suggestion
    return LLVMBuildCall2(st->builder, function_type, function, args, nargs, debug_name);
```

File: src/codegen.c [hunk 7]
```diff
@@ -93,212 +99,142 @@ static LLVMValueRef make_a_string_constant(const struct State *st, const char *s
...
-
-    case AST_STMT_RETURN_WITHOUT_VALUE:
-        LLVMBuildRetVoid(st->builder);
-        break;
-
-    case AST_STMT_EXPRESSION_STATEMENT:
-        codegen_expression(st, &stmt->data.expression);
-        break;
+#define set(var,val) set_local_var(st, (var), (val))
+#define setdest(val) set(ins->destvar, (val))
```
Comment (Akuli) [inline src/codegen.c:121]:
```suggestion
#define setdest(val) set_local_var(st, ins->destvar, (val))
```

File: src/codegen.c [hunk 8]
```diff
@@ -93,212 +99,142 @@ static LLVMValueRef make_a_string_constant(const struct State *st, const char *s
...
+        case CF_INT_MUL: setdest(LLVMBuildMul(st->builder, getop(0), getop(1), name)); break;
+        case CF_INT_SDIV: setdest(LLVMBuildSDiv(st->builder, getop(0), getop(1), name)); break;
+        case CF_INT_UDIV: setdest(LLVMBuildUDiv(st->builder, getop(0), getop(1), name)); break;
+        case CF_INT_EQ: setdest(LLVMBuildICmp(st->builder, LLVMIntEQ, getop(0), getop(1), name)); break;
+        // TODO: unsigned less-than
+        case CF_INT_LT: setdest(LLVMBuildICmp(st->builder, LLVMIntSLT, getop(0), getop(1), name)); break;
+        case CF_VARCPY: setdest(getop(0)); break;
     }
+
+#undef set
```
Comment (Akuli) [inline src/codegen.c:164]:
```suggestion
```

File: src/free.c [hunk 9]
```diff
@@ -121,6 +121,18 @@ static void free_signature(const struct AstFunctionSignature *sig)
     free(sig->argnames);
 }
 
+static void free_cfg(struct CfGraph *cfg)
+{
+    for (struct CfBlock **b = cfg->all_blocks.ptr; b < End(cfg->all_blocks); b++) {
+        // TODO
+        //free((*b)->expressions.ptr);
```
Comment (Akuli) [inline src/free.c:128]: should do

File: src/jou_compiler.h [hunk 10]
```diff
@@ -175,7 +175,11 @@ struct AstFunctionDef {
     // Local variables are added during fill_types.
     // First n local variables are the function arguments.
     // End of list is denoted with empty name.
+    // TODO: delete dis
```
Comment (Akuli) [inline src/jou_compiler.h:178]:
```suggestion
    // TODO: delete this
```

File: src/jou_compiler.h [hunk 11]
```diff
@@ -175,7 +175,11 @@ struct AstFunctionDef {
...
     struct AstLocalVariable { char name[100]; struct Type type; } *locals;
+
+    // Initially NULL. Created in a separate compilation step after parsing and fill_types.
+    struct CfGraph *cfg;
```
Comment (Akuli) [inline src/jou_compiler.h:182]: Probably shouldn't attach CFG to ast, should be a separate thing

File: src/jou_compiler.h [hunk 12]
```diff
@@ -193,6 +197,61 @@ struct AstToplevelNode {
...
+struct CfBlock {
+    List(struct CfInstruction) instructions;
+    struct CfVariable *branchvar;  // boolean value used to decide where to jump next
+    struct CfBlock *iftrue;
+    struct CfBlock *iffalse;
+};
+
+struct CfGraph {
+    struct CfBlock start_block;  // First block
+    struct CfBlock end_block;  // Return statement
```
Comment (Akuli) [inline src/jou_compiler.h:249]:
```suggestion
    struct CfBlock end_block;  // Always empty. Return statement jumps here.
```

File: src/print.c [hunk 13]
```diff
@@ -258,6 +258,149 @@ static void print_ast_body(const struct AstBody *body, int indent)
...
+        printf("%s", v->name);
+    else {
+        for (int i = 0; i < cfg->variables.len; i++) {
+            if (cfg->variables.ptr[i] == v) {
+                printf("var%d", i);
+                return;
+            }
+        }
+        assert(0);
+    }
```
Comment (Akuli) [inline src/print.c:275]: This is no longer needed

File: tests/should_succeed/return_void.jou [hunk 14]
```diff
@@ -5,11 +5,13 @@ def foo() -> void:
     putchar('i')
     putchar('\n')
 
-def should_do_nothing() -> void:
-    return
+# The skip argument is needed to prevent compile error about dead code.
```
Comment (Akuli) [inline tests/should_succeed/return_void.jou:8]:
```suggestion
# In the future, the skip argument will be needed to prevent compile error about dead code.
```
